# frozen_string_literal: true

require_relative 'lib/json_mend/version'

Gem::Specification.new do |spec|
  spec.name = 'json_mend'
  spec.version = JsonMend::VERSION
  spec.authors = ['Oleksii Vasyliev']
  spec.email = ['leopard.not.a@gmail.com']

  spec.summary = 'Repair broken JSON'
  spec.description = [
    'JsonMend is a robust Ruby gem designed to repair broken or malformed JSON strings.',
    'It is specifically optimized to handle common errors found in JSON generated by Large Language Models (LLMs),',
    'such as missing quotes, trailing commas, unescaped characters, and stray comments'
  ].join(' ')
  spec.homepage = 'https://github.com/le0pard/json_mend'
  spec.required_ruby_version = '>= 3.1.0'

  spec.metadata['homepage_uri'] = spec.homepage
  spec.metadata['source_code_uri'] = 'https://github.com/le0pard/json_mend'
  spec.metadata['changelog_uri'] = 'https://github.com/le0pard/json_mend/releases'
  spec.metadata['rubygems_mfa_required'] = 'true'

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  gemspec = File.basename(__FILE__)
  spec.files = IO.popen(%w[git ls-files -z], chdir: __dir__, err: IO::NULL) do |ls|
    ls.readlines("\x0", chomp: true).reject do |f|
      (f == gemspec) ||
        f.start_with?(*%w[bin/ test/ spec/ features/ .git .github appveyor Gemfile])
    end
  end
  spec.bindir = 'exe'
  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ['lib']

  spec.add_dependency 'json', '>= 0'
  spec.add_dependency 'strscan', '>= 0'
end
